function draw_circles(pt)
for i=1:size(pt,1)
  rectangle('Position', ...
            [pt(i,1)-pt(i,3), pt(i,2)-pt(i,3), 2 * pt(i,3), 2* pt(i,3)],...
            'Curvature', [1, 1], 'EdgeColor', 'r', ...
            'LineWidth', 2);
end
