% image directory for positive examples
centroid_file = 'images/centroid_features_bg_1'
svm_tf = 'svm_train_bg_2'
svm_pm = 'svm_param_bg_2'
svm_pd = 'svm_predict_bg_2'
cf_mat = [centroid_file, '.mat']
max_points = 10
threshold = 0.2

assert(ischar(cf_mat))

process('images/T01_bark1', 'images/T16_glass1', svm_tf,...
        svm_pm, 'centroid_file', centroid_file,...
        'desc', 'rift', 'keypt', 'hl', 'threshold', threshold, 'max_points', max_points)
test_model('images/T02_bark2/', 'images/T17_glass2/', 'svm_test_bg',...
           cf_mat, svm_pm, svm_pd ,...
           'desc', 'rift', 'keypt', 'hl', 'threshold', threshold, ...
           'max_points', max_points)

% % the above generates a keypoint file and so I'll use those and input
% % what they should be in the things running below
% process('images/T01_bark1', 'images/T16_glass1', 'svm_train_bg_spin',...
%         'svm_param_bg_spin', 'centroid_file', 'images/centroid_features_bg_spin',...
%         'desc', 'spin',...
%         'keypt_file', 'ASDFASDFASDF')
% test_model('images/T02_bark2/', 'images/T17_glass2/', 'svm_test_bg_spin',...
%            'images/centroid_features_bg_spin.mat', 'svm_param_bg_spin', 'svm_predict_bg_spin',...
%            'desc', 'spin',...
%            'keypt_file', 'ASDFASDFASDFASDF')

