% load the path 
project_path

% image directory for positive examples
pos_train = 'images/T01_bark1_points_train_bg1'
neg_train = 'images/T16_glass1_points_train_bg1'

pos_test = 'images/bark1_test_points_test_bg2'
neg_test = 'images/glass1_test_points_test_bg2'

svm_tf = 'svm_train_bg_2'
svm_pm = 'svm_param_bg_2'
svm_pd = 'svm_predict_bg_2'
max_points = 1000
threshold = 0.2
desc = 'rift'
keypt = 'hl'
have_pts = true
cl_algo = 'nb'

[classifier centroids] = train_model(pos_train, neg_train , svm_tf, svm_pm,...
                                     'ext', 'train_bg1', ...
                                     'desc', desc, 'keypt', keypt, ...
                                     'threshold', threshold, ...
                                     'max_points', max_points,...
                                     'have_pts', have_pts,...
                                     'cl_algo', cl_algo);
classifier
have_pts = true;
[e, output] = test_model(classifier, pos_test, neg_test, 'svm_test_bg',...
                         centroids, svm_pd ,...
                         'desc', desc, 'keypt', keypt,...
                         'threshold', threshold, ...
                         'max_points', max_points,...
                         'ext', 'test_bg2',...
                         'have_pts', have_pts);
e
